symptoms = [
                "Itching", "Skin redness", "Hives or rash", "Sneezing", "Runny nose", 
                "Itchy, watery eyes", "scratchy throat", "difficulty breathing", "wheezing",
                "skin reactions, including hives and itching", "difficulty breathing",
                "swelling of the throat and tongue",
                "weak, rapid pulse", "nausea, vomiting/diarrhoea", "fainting/dizziness",
                "skin reactions, including hives and itching", "difficulty breathing",
                "loss of consciousness",
                "Sneezing", "runny nose", "itchy, red, watery eyes", "nasal congestion", 
                "itchy nose, roof or mouth or throat", "postnasal drip", "cough", 
                "facial pressure and pain", "frequent awakening", 
                "swollen, blue-colored skin under the eyes", "frequent upward rubbing of the nose",
                "Fever and chills", "A cough that brings up blood (hemoptysis)", 
                "Shortness of breath", "Chest or joint pains", "Headaches or eye symptoms",
                "skin lesions", "fatigues", "untintentional weight loss", "wheezing",
                "Sneezing", "runny nose", "itchy, red, watery eyes", "nasal congestion", 
                "itchy nose, roof or mouth or throat", "postnasal drip", "cough", 
                "facial pressure and pain", "frequent awakening", 
                "swollen, blue-colored skin under the eyes", "frequent upward rubbing of the nose",
                "Tingling or itching in the mouth", "Hives, itching or eczema", 
                "Swelling of lips, face, tongue, throat", "wheezing", "nasal congestion", 
                "Abdominal pain, diarrhoea, nausea, vomiting",
                "dizziness, lightheadedness or fainting"
        ]
