recommendations = [
        "Take a prenatal vitamin",
        "Exercise regularly",
        "Write a birth plan",
        "Educate yourself",
        "Change your chores (avoid harsh or toxic cleaners, heavy lifting)",
        "Track your weight gain (normal weight gain is 25 - 35 pounds)",
        "Get comfortable shoes",
        "Eat folate-rich foods (lentils, asparagus, oranges, fortified cereals)",
        "Eat calcium-rich foods (dairy, canned fish, soy)",
        "Eat more fish (except those high in mercury)",
        "Eat foods with fiber",
        "Don't eat soft cheeses",
        "Eat your veggies",
        "Eat five or six well-balanced meals each day",
        "Don't overeat. You only need 300-500 additional calories per day. Keep a food dairy.",
        "Limit caffeine",
        "Drink plenty of fluids (six 8-ounce glasses of water per day)",
        "Don't drink alcohol",
        "Wear sunscreen",
        "Fly smart (avoid air travel if possible early and late in the pregnancy)",
        "Avoid changing cat litter (to reduce risk of toxoplasmosis)",
        "Give in to cravings (sometimes)",
        "Know when to call your doctor with concerns",
        "Don't smoke; avoid secondhand smoke",
        "Get enough sleep",
        "Wear a seatbelt",
        "Don't take over-the-counter medications or herbal remedies without medical consultation",
        "See your dentist",
        "Take a pregnancy class",
        "Baby sit a friend's baby for some real-world experience",
        "Tour birth facilities",
        "Practice relaxation techniques daily (yoga, stretching, deep breathing, massage)",
        "Don't overmedicate",
        "Exercise, but don't overdo it",
        "Stretch before bed to avoid leg cramps",
        "Take a picture of yourself before the baby arrives"
        ]
