parts = [
        ["Anus", "The opening of the rectum to the outside of the body."],
        ["Arteries", "Tubelike structures that are responsible for the transportation"],
        ["Appendix", "A small, thin pouch about 5 to 10 cm long."],
        ["Adrenal glands", "Small, triangular-shaped glands located on top of both kidneys."],
        ["Brain", "A complex organ that controls thought, memory, emotion, touch, motor skills, vision, breathing, temperature, hunger, and every other process that regulates our body."],
        ["Bones", "Hard whitish tissue making up the skeleton in humans and other vertebrates."],
        ["Bronchi", "The large tubes that connect to your trachea and direct the air you breathe to your right and left lungs."],
        ["Bladder", "A muscular sac in the pelvis, just above and behind the pubic bone."],
        ["Bone Marrow", "Found in the center of most bones and has many blood vessels."],
        ["Bulbourethal glands", "Also known as Cowper's glands. Either of the two pea-shaped glands in the male, found beneath the prostate glands at the beginning of the internal portion of the penis."],
        ["Colon", "The longest part of the large intestine."],
        ["Cervix", "The lower, narrow end of the uterus that forms a canal between the uterus and vagina."],
        ["Clitoris", "A bulb shaped sexual organ that's part of the female reproductive system. It's the most sensitive erogenous zone."],
        ["Eyes", "Organss of the visual system."],
        ["Fallopian Tubes", "One of the two long, slender tubes that connect the ovaries to the uterus."],
        ["Genitals", "The external organs of reproduction."],
        ["Gall bladder", "A sac located under the liver. It stores and concetrates the bile produced by the liver."],
        ["Heart", "A muscular organ that pumps blood through the blood vessels of the circulatory system."],
        ["Hair Follicle", "A shaft or opening on the surface of the skin throught which hair grows."],
        ["Hypothalamus", "A structure deep in the brain that acts as the body's smart control coordinating center."],
        ["Interstitium", "A contiguous fluid-filled space existing between a structural barrier, such as a cell membrane or the skin, and internal structures."],
        ["Kidneys", "A pair of bean-shaped organs on either side of the spine below the ribs and behind the belly used for osmoregulation."],
        ["Ligaments", "A fibrous connective tissue that attaches bone to bone."],
        ["Lymph Nodes", "A small bean-shaped structure that is part of the body's immune system."],
        ["Large Intestine", "A long, tube-like organ that is connected to the small intentine at one end and the anus at the other."],
        ["Mouth", "The opening in the lower part of the human face, sorrounded by lips, thrpugh which food is taken in and vocal sounds are emitted."],
        ["Mesentery", "A fold of membrane that attaches the intestine to the abdominal wall and holds it in place."],
        ["Mammary glands", "Glandular organ located on the chest. Can make milk."],
        ["Nose", "The part projecting above the mouth of the face of a person or animal, containing the nostril, used for breathing and smelling."],
        ["Penis", "Male sexual organ, performing sexual functions and urinary functions."],
        ["Pancreas", "An organ and gland that performs exocrine and endocrine functions."],
        ["Pharynx", "The hollow tube inside the neck that starts behind the nose and ends at the top of the trachea and eosophagus."],
        ["Placenta", "An organ that develops in the uterus during pregnancy."],
        ["Prostrate", "A part of the male reproductive system, which includes the penis, prostate, seminal vesicles and testicles."],
        ["Pineal Gland", "A tiny gland in your brain that's located beneath the back of the corpus callossum"],
        ["Parathyroid glands", "Glands located behind the thyroid at the bottom of your neck."],
        ["Rectum", "The last several inches of the large intestine closest to the anus."],
        ["Salivary Glands", "Glands that produce saliva and empty it into your mouth ducts, or small openings."],
        ["Skeletal Muscles", "Organs of the vertebrate muscular system and typically attached to bones of a skeleton."],
        ["Seminal Vesicles", "Glands that produce the fluids that turn into semen."],
        ["Subcutaneous Tissue", "Bottom layer of the skin in your body that insulates the body, protects the body from harm and stores energy, and connects skin to muscles and bones."],
        ["Teeth", "Hard substances that mechanically break down items of food by cutting and crushing them in preparation for swallowing and digesting."],
        ["Tonsils", "Lymph nodes in the back of the mouth and top the throat."],
        ["Testes", "One of two egg-shaped glands inside the scrotum that produce sperm and male hormones."],
        ["Vestigial Organ", "Rudimentary anatomical structures that are retained in a species despite having lost their primary ancestral function."],
        ["Vas Deferens", "A coiled tube that carries the sperm out of the testes."],
        ["Vagina", "A flexible tube that joins the uterus to the vulva."],
        ["Veins", "Blood vessels located throughout your body that collect oxygen-poor blood return it to the heart"],
        ["Vulva", "The outer part of the female genitals. Includes the opening of the vagina (vestibule), the labia majora (outer lips), the labia minora (inner lips), and clitoris."],
        ["Uterus", "The hollow, pear-shaped organ in a woman's pelvis where the fetus develops and grows."],
        ["Urethra", "The tube through which urine leaves the body."],
        ["Ureters", "The tube that carries urine from the kidney to the bladder."],
        ["Thymus Gland", "A small gland in the lymphatic system that makes and trains special white blood cells called T-Cells that help the immune system fight disease and infection."],
        ["Trachea", "The airway that leads from the larynx to the bronchi."],
        ["Tongue", "A digestive organ that moves food around the moputh to help chew and swallow."], 
        ["Skin", "The largest organ that covers the entire body and serves as the protective shield against heat, light, injury and infection."],
        ["Spleen", "An abdominal organ involved in the production and removal of blood cells in most vertebrates forming pary of the immune system."],
        ["Scrotum", "Part of the male's body that is located below the penis and contains the testes, epididymis, and the lower part of the spermadic cord."],
        ["Stomach", "A large muscular and hollow organ allowing for a capacity to hold food."],
        ["Spinal Cord", "A structure that extends downwards from the base of the brain that is made up of the nerve cells and groups of nerves that carry messages betwen the brain and the rest of the body."],
        ["Small Intestine", "The duodenum, jejunum, and ileum."],
        ["Nerves", "Like cables that carry electrical impulses between the brain and the rest of the body."],
        ["Nasal Cavity", "The space inside the nose that forms the roof of the mouth and curves down at the back to join the throat."],
        ["Ovaries", "One of the pair of female glands in which the eggs form and the female hormones estrogen and progesterone are made."],
        ["Oesophagus/ Esophagus", "A hollow muscular tube that connects the back of the throat to the top of the stomach."],
        ["Lungs", "Each of the pair of organs situated within the ribcage, consisting of elastic sacs with branching passages into which air is drawn, so that oxygen can pass into the blood and carbon-dioxide removed."]
        ]
