#source https://www.nhs.uk/conditions/miscarriage/causes/
causes = [
        'Chromosomal problems',
        'Placenta problems',
        'Alcohol intake and drug abuse',
        'Obesity',
        'Drinking lots of caffeine',
        'Long-term health condition - diabetes',
        'Long-term health condition - high blood pressure',
        'Long-term health condition - lupus',
        'Long-term health condition - kidney disease',
        'Long-term health condition - overactive thyroid gland (hyperthyroidism',
        'Long-term health condition - underactive thyroid gland (hypothyroidism)',
        'Long-term health condition - antiphospholipid syndrom (APS)',
        'Rubella (German measles)',
        'Cytomelagovirus (CMV)',
        'Bacterial vaginosis',
        'HIV',
        'Chlamydia',
        'Gonorrhoea',
        'Syphillis',
        'Malaria',
        'Food Poisoning - (listeriosis/ toxoplasmosis/ salmonella)',
        'Medicines - misprostol',
        'Medicines - retinoids',
        'Medicines - methotrexate',
        'Medicines - non-steroidal anti-inflammatory drugs (NSAID)',
        'Problematic or abnormal womb',
        'Weakened cervix',
        'Polycystic ovary syndrome (PCOS)'
        ]
